#!/usr/bin/env python3
"""
Generate a complete React demo application
"""

import asyncio
import json
from pathlib import Path
from src.tools import javascript_tools
from src.tool_schemas import (
    GenerateReactComponentInput,
    GenerateNextJSPageInput,
    GenerateAPIRouteInput
)


async def generate_demo():
    """Generate complete React demo"""
    print("=" * 60)
    print("Generating React Demo Application")
    print("=" * 60)
    
    demo_dir = Path("demo")
    
    # Create demo directory structure
    print("\n1. Creating directory structure...")
    (demo_dir / "src" / "components").mkdir(parents=True, exist_ok=True)
    (demo_dir / "src" / "app").mkdir(parents=True, exist_ok=True)
    (demo_dir / "src" / "app" / "api").mkdir(parents=True, exist_ok=True)
    (demo_dir / "public").mkdir(parents=True, exist_ok=True)
    print("   ✓ Directories created")
    
    # Generate components
    print("\n2. Generating React components...")
    
    components = [
        {
            "name": "Header",
            "props": [
                {"name": "title", "type": "string"},
                {"name": "subtitle", "type": "string"}
            ]
        },
        {
            "name": "Footer",
            "props": [
                {"name": "year", "type": "number"},
                {"name": "company", "type": "string"}
            ]
        },
        {
            "name": "Card",
            "props": [
                {"name": "title", "type": "string"},
                {"name": "description", "type": "string"},
                {"name": "imageUrl", "type": "string"}
            ]
        },
        {
            "name": "Button",
            "props": [
                {"name": "label", "type": "string"},
                {"name": "onClick", "type": "() => void"},
                {"name": "variant", "type": "'primary' | 'secondary'"}
            ]
        }
    ]
    
    for comp in components:
        params = GenerateReactComponentInput(
            component_name=comp["name"],
            component_type="functional",
            use_typescript=True,
            props=comp["props"],
            styling="tailwind",
            output_dir=str(demo_dir / "src" / "components")
        )
        result = await javascript_tools.generate_react_component(params)
        if result.success:
            print(f"   ✓ {comp['name']} component generated")
        else:
            print(f"   ✗ Failed to generate {comp['name']}: {result.error}")
    
    # Generate pages
    print("\n3. Generating Next.js pages...")
    
    pages = [
        {"name": "home", "route": "/"},
        {"name": "about", "route": "/about"},
        {"name": "demo", "route": "/demo"}
    ]
    
    for page in pages:
        params = GenerateNextJSPageInput(
            page_name=page["name"],
            route=page["route"],
            use_typescript=True,
            output_dir=str(demo_dir / "src" / "app")
        )
        result = await javascript_tools.generate_nextjs_page(params)
        if result.success:
            print(f"   ✓ {page['name']} page generated")
        else:
            print(f"   ✗ Failed to generate {page['name']}: {result.error}")
    
    # Generate API route
    print("\n4. Generating API routes...")
    params = GenerateAPIRouteInput(
        route_name="hello",
        method="GET",
        use_typescript=True,
        framework="nextjs",
        output_dir=str(demo_dir / "src" / "app" / "api")
    )
    result = await javascript_tools.generate_api_route(params)
    if result.success:
        print(f"   ✓ API route generated")
    else:
        print(f"   ✗ Failed to generate API route: {result.error}")
    
    # Generate package.json
    print("\n5. Generating package.json...")
    package_json = {
        "name": "ai-agent-demo",
        "version": "1.0.0",
        "description": "Demo React application generated by AI Coding Agent",
        "scripts": {
            "dev": "next dev",
            "build": "next build",
            "start": "next start",
            "lint": "next lint"
        },
        "dependencies": {
            "react": "^18.2.0",
            "react-dom": "^18.2.0",
            "next": "^14.0.0",
            "typescript": "^5.3.0",
            "@types/react": "^18.2.0",
            "@types/node": "^20.10.0"
        },
        "devDependencies": {
            "tailwindcss": "^3.4.0",
            "postcss": "^8.4.0",
            "autoprefixer": "^10.4.0",
            "@types/react-dom": "^18.2.0",
            "eslint": "^8.55.0",
            "eslint-config-next": "^14.0.0"
        }
    }
    
    with open(demo_dir / "package.json", "w") as f:
        json.dump(package_json, f, indent=2)
    print("   ✓ package.json created")
    
    # Generate tsconfig.json
    print("\n6. Generating tsconfig.json...")
    tsconfig = {
        "compilerOptions": {
            "target": "ES2020",
            "lib": ["dom", "dom.iterable", "esnext"],
            "allowJs": True,
            "skipLibCheck": True,
            "strict": True,
            "forceConsistentCasingInFileNames": True,
            "noEmit": True,
            "esModuleInterop": True,
            "module": "esnext",
            "moduleResolution": "bundler",
            "resolveJsonModule": True,
            "isolatedModules": True,
            "jsx": "preserve",
            "incremental": True,
            "plugins": [{"name": "next"}],
            "paths": {
                "@/*": ["./src/*"]
            }
        },
        "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
        "exclude": ["node_modules"]
    }
    
    with open(demo_dir / "tsconfig.json", "w") as f:
        json.dump(tsconfig, f, indent=2)
    print("   ✓ tsconfig.json created")
    
    # Generate tailwind.config.js
    print("\n7. Generating tailwind.config.js...")
    tailwind_config = """/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
"""
    with open(demo_dir / "tailwind.config.js", "w") as f:
        f.write(tailwind_config)
    print("   ✓ tailwind.config.js created")
    
    # Generate next.config.js
    print("\n8. Generating next.config.js...")
    next_config = """/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
}

module.exports = nextConfig
"""
    with open(demo_dir / "next.config.js", "w") as f:
        f.write(next_config)
    print("   ✓ next.config.js created")
    
    # Generate postcss.config.js
    print("\n9. Generating postcss.config.js...")
    postcss_config = """module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
"""
    with open(demo_dir / "postcss.config.js", "w") as f:
        f.write(postcss_config)
    print("   ✓ postcss.config.js created")
    
    # Generate global CSS
    print("\n10. Generating global styles...")
    global_css = """@tailwind base;
@tailwind components;
@tailwind utilities;

body {
  margin: 0;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen',
    'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue',
    sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
"""
    (demo_dir / "src" / "app").mkdir(parents=True, exist_ok=True)
    with open(demo_dir / "src" / "app" / "globals.css", "w") as f:
        f.write(global_css)
    print("   ✓ globals.css created")
    
    # Generate layout.tsx
    print("\n11. Generating root layout...")
    layout_tsx = """import './globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'AI Agent Demo',
  description: 'Demo application generated by AI Coding Agent',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
"""
    with open(demo_dir / "src" / "app" / "layout.tsx", "w") as f:
        f.write(layout_tsx)
    print("   ✓ layout.tsx created")
    
    # Generate README
    print("\n12. Generating README...")
    readme = """# AI Agent Demo Application

This is a demo React/Next.js application generated by the AI Coding Agent.

## Features

- ✅ Next.js 14 with App Router
- ✅ TypeScript
- ✅ Tailwind CSS
- ✅ React Components (Header, Footer, Card, Button)
- ✅ Multiple Pages (Home, About, Demo)
- ✅ API Routes

## Getting Started

### Install Dependencies

```bash
npm install
```

### Run Development Server

```bash
npm run dev
```

Open [http://localhost:3000](http://localhost:3000) in your browser.

### Build for Production

```bash
npm run build
npm start
```

## Project Structure

```
demo/
├── src/
│   ├── app/              # Next.js pages and routes
│   │   ├── home/         # Home page
│   │   ├── about/        # About page
│   │   ├── demo/         # Demo page
│   │   ├── api/          # API routes
│   │   ├── layout.tsx    # Root layout
│   │   └── globals.css   # Global styles
│   └── components/       # React components
│       ├── Header.tsx
│       ├── Footer.tsx
│       ├── Card.tsx
│       └── Button.tsx
├── public/               # Static assets
├── package.json
├── tsconfig.json
├── tailwind.config.js
└── next.config.js
```

## Generated by

AI Coding Agent - Groq-powered React/TypeScript code generator
"""
    with open(demo_dir / "README.md", "w") as f:
        f.write(readme)
    print("   ✓ README.md created")
    
    print("\n" + "=" * 60)
    print("✓ Demo application generated successfully!")
    print("=" * 60)
    print(f"\nLocation: {demo_dir.absolute()}")
    print("\nNext steps:")
    print("  1. cd demo")
    print("  2. npm install")
    print("  3. npm run dev")
    print("\nThen open http://localhost:3000 in your browser")


if __name__ == "__main__":
    asyncio.run(generate_demo())
